/*
 * Copyright 2000-2025 Heinz Max Kabutz
 * All rights reserved.
 *
 * From The Java Specialists' Newsletter (https://www.javaspecialists.eu)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package eu.javaspecialists.tjsn.issue095;

import java.io.*;
import java.util.*;

public class XMLFileConfiguration extends AbstractConfiguration {
    private final File file;
    private long lastModified = 0;

    public XMLFileConfiguration(Properties defaults, String filename, int period)
            throws IOException {
        super(period);
        setAllProperties(defaults);
        file = new File(filename);
        if (!file.exists()) {
            storeProperties();
        }
        loadProperties();
    }

    private void loadProperties() throws IOException {
        Properties properties = new Properties();
        properties.loadFromXML(new FileInputStream(file));
        setAllProperties(properties);
    }

    private void setAllProperties(Properties properties) {
        for (Map.Entry<Object, Object> entry : properties.entrySet()) {
            setProperty((String) entry.getKey(), entry.getValue());
        }
    }

    public void storeProperties() {
        Properties properties = new Properties();
        for (Map.Entry<String, Object> entry : getAllProperties()) {
            properties.put(entry.getKey(), entry.getValue());
        }
        try {
            properties.storeToXML(new FileOutputStream(file),
                    "Generated by XMLFileConfiguration");
        } catch (IOException e) {
            Exceptions.throwException(e);
        }
    }

    protected void checkForPropertyChanges() {
        if (lastModified != file.lastModified()) {
            try {
                lastModified = file.lastModified();
                loadProperties();
            } catch (IOException e) {
                Exceptions.throwException(e);
            }
        }
    }
}
